- title: Zero to App Store
  best_if: you need brand new Hotwire Native apps and want me to do everything.
  you_get: a developer (me!) to build your iOS and Android apps and launch them.
  cta: Email Joe to get started
  description: |
    I write all of the native Swift/Kotlin code and Rails integration needed. We can
    integrate with native Apple/Android SDKs, too. I work with your designers and
    developers to teach and apply the best practices I've accumulated working
    with the framework for 10+ years.

- title: Private custom workshop
  best_if: you want to level up your team to write Hotwire Native apps on their own.
  you_get: a custom workshop tailored to your team's unique needs and skill level.
  cta: Email Joe to get started
  description: |
    Workshops can range from virtual, half-day sessions to in-person, multi-day
    events.  They can cover Swift/Kotlin syntax, dive right into the Hotwire
    Native integration, or skip ahead to best practices in building scalable
    hybrid apps with small teams.

- title: Monthly advisory retainer
  best_if: you want to write the code yourself but need an expert to guide you.
  you_get: unlimited access to me via phone, email, and/or Zoom.
  cta: Email Joe to get started
  description: |
    Use our time to get advice on best practices, receive technical overviews of
    topics, or even to dive into your Hotwire Native code. I return all messages
    no later than the next business day. Meetings must be scheduled in advance.

- title: Pair with Joe
  price: $499 for a 90 minute pairing session
  best_if: you have specific questions on your Hotwire Native app.
  you_get: a hands-on pairing session with a Hotwire Native expert.
  href: https://savvycal.com/joemasilotti/pair
  cta: Schedule a meeting
  description: |
    A private 90-minute pairing session with me. Use our time to dive into a
    specific question or problem you're having with your Hotwire Native app.
    Limited to one session per month per individual/business.
